[tox]
envlist=
    py{310,311,312,313,314},
    flake8,
    mypy

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
deps=
    sphinx >= 4.4
extras=
    test
    loader
setenv =
    PYTHONWARNINGS = all
    #,ignore::DeprecationWarning:docutils.io
commands=
    {envpython} -m pytest tests {posargs}

[testenv:flake8]
description =
    Run style checks.
extras =
    test
    lint
commands=
    flake8 src/

[testenv:mypy]
description =
    Run type checks.
deps=
    types-PyYAML
    types-docutils
extras =
    test
    lint
commands=
    mypy src/

[flake8]
# compatible with black formatting
max-line-length = 88
# whitespace before ':' should be allowed (black)
# W503 is not PEP8 compliant. Not sure where it is being enabled.
ignore = E203,W503

[pycodestyle]
# compatible with black formatting
max-line-length = 88
# whitespace before ':' should be allowed (black)
ignore = E203
